apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: toggle-apps
resources:
  - ../../../base/evaluation-service
images:
  - name: acrtogglemasterprod6k07.azurecr.io/evaluation-service
    newTag: latest
commonAnnotations:
  teste-gitops: "sync-check-1"
