trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - terraform/**
      - README.md

variables:
  azureServiceConnection: 'sc-azure-togglemaster'
  acrRegistry: 'acrtogglemaster.azurecr.io'
  aksResourceGroup: 'rg-togglemaster-prod'
  aksCluster: 'aks-togglemaster-prod'
  tag: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: 'Build & Push Docker Images'
    jobs:
      - job: BuildServices
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Auth:
              serviceName: 'auth-service'
              dockerfilePath: 'auth-service/Dockerfile'
            Flag:
              serviceName: 'flag-service'
              dockerfilePath: 'flag-service/Dockerfile'
            Targeting:
              serviceName: 'targeting-service'
              dockerfilePath: 'targeting-service/Dockerfile'
            Evaluation:
              serviceName: 'evaluation-service'
              dockerfilePath: 'evaluation-service/Dockerfile'
            Analytics:
              serviceName: 'analytics-service'
              dockerfilePath: 'analytics-service/Dockerfile'
        steps:
          - task: Docker@2
            displayName: 'Build & Push $(serviceName)'
            inputs:
              containerRegistry: 'sc-acr-togglemaster'
              repository: '$(serviceName)'
              command: 'buildAndPush'
              Dockerfile: '$(dockerfilePath)'
              tags: |
                $(tag)
                latest

  - stage: DeployToK8s
    displayName: 'Deploy to AKS'
    dependsOn: BuildAndPush
    jobs:
      - deployment: Deploy
        environment: 'Production-K8s'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: KubernetesManifest@1
                  displayName: 'Deploy Namespaces and Ingress'
                  inputs:
                    action: 'deploy'
                    connectionType: 'azureResourceManager'
                    azureSubscriptionConnection: '$(azureServiceConnection)'
                    azureResourceGroup: '$(aksResourceGroup)'
                    kubernetesCluster: '$(aksCluster)'
                    manifests: |
                      K8S_AKS/00-namespaces.yaml
                      K8S_AKS/ingress/ingress.yaml

                - task: KubernetesManifest@1
                  displayName: 'Deploy Microservices & Jobs'
                  inputs:
                    action: 'deploy'
                    connectionType: 'azureResourceManager'
                    azureSubscriptionConnection: '$(azureServiceConnection)'
                    azureResourceGroup: '$(aksResourceGroup)'
                    kubernetesCluster: '$(aksCluster)'
                    namespace: 'togglemaster'
                    manifests: |
                      K8S_AKS/auth-service/deployment.yaml
                      K8S_AKS/auth-service/service.yaml
                      K8S_AKS/auth-service/migration-job.yaml
                      K8S_AKS/flag-service/deployment.yaml
                      K8S_AKS/flag-service/service.yaml
                      K8S_AKS/flag-service/migration-job.yaml
                      K8S_AKS/targeting-service/deployment.yaml
                      K8S_AKS/targeting-service/service.yaml
                      K8S_AKS/targeting-service/migration-job.yaml
                      K8S_AKS/evaluation-service/deployment.yaml
                      K8S_AKS/evaluation-service/service.yaml
                      K8S_AKS/analytics-service/deployment.yaml
                      K8S_AKS/analytics-service/service.yaml
                      K8S_AKS/scaling/hpa-evaluation.yaml
                      K8S_AKS/scaling/hpa-analytics.yaml
                    containers: |
                      $(acrRegistry)/auth-service:$(tag)
                      $(acrRegistry)/flag-service:$(tag)
                      $(acrRegistry)/targeting-service:$(tag)
                      $(acrRegistry)/evaluation-service:$(tag)
                      $(acrRegistry)/analytics-service:$(tag)