apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: toggle-apps
resources:
  - ../../../base/flag-service
images:
  - name: fiapdevopsadegj.azurecr.io/flag-service
    newTag: latest
