apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: toggle-apps
  labels:
    app: targeting-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://USER:PASSWORD@HOST:5432/targeting_db?sslmode=require"
