apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: togglemaster
  source:
    repoURL: 'https://dev.azure.com/Oh20Tony/FIAP%20-%20TechChallenge/_git/TCF3%20-%20K8S'
    targetRevision: main
    path: overlays/dev/auth-service
  destination:
    server: 'https://fiaptc3-dns-l25hulwg.hcp.eastus.azmk8s.io:443'
    namespace: toggle-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        projeto: togglemaster
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
