apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: togglemaster
  source:
    repoURL: 'https://dev.azure.com/Oh20Tony/FIAP%20-%20TechChallenge/_git/FIAP%20-%20ToggleMaster%20F3'
    targetRevision: main
    path: Infra/GitOps/dev/platform
  destination:
    server: 'https://fiaptc3-dns-l25hulwg.hcp.eastus.azmk8s.io:443'
    namespace: toggle-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        projeto: togglemaster
