apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: toggle-apps
  labels:
    app: analytics-service
data:
  PORT: "8005"
  SERVICE_BUS_QUEUE_NAME: "togglemasterqueue"
  COSMOS_ENDPOINT: "https://tohhlemaster-analytics.documents.azure.com:443/"
  COSMOS_DATABASE: "ToggleMaster"
  COSMOS_CONTAINER: "ToggleMasterAnalytics"
