apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: toggle-apps
  labels:
    app: evaluation-service
type: Opaque
stringData:
  REDIS_URL: "rediss://:KEY_URL_ENCODED@SEU-REDIS.redis.azure.net:10000"
  SERVICE_API_KEY: "tm_key_PREENCHER"
  SERVICE_BUS_CONNECTION_STRING: "Endpoint=sb://SEU-NAMESPACE.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SUA-CHAVE"
