apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-apps

resources:
  - ../../../K8S_AKS/evaluation-service

images:
  - name: fiapdevopsadegj.azurecr.io/evaluation-service
    newTag: latest
