apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: toggle-apps
  labels:
    app: flag-service
data:
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service.toggle-apps"
