apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: toggle-apps
resources:
  - ../../../base/analytics-service
images:
  - name: fiapdevopsadegj.azurecr.io/analytics-service
    newTag: latest
