apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: toggle-apps
resources:
- ../../../base/targeting-service
images:
- name: acrtogglemasterprod62g6.azurecr.io/targeting-service
  newName: acrtogglemasterprod62g6.azurecr.io/targeting-service
  newTag: 8-2d04edd
