# Recursos compartilhados: Ingress e HPAs. Separados dos servicos porque nao
# mudam a cada build e nao carregam tag de imagem.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: togglemaster

  source:
    repoURL: 'https://dev.azure.com/Oh20Tony/FIAP%20-%20TechChallenge/_git/TCF3%20-%20K8S'
    targetRevision: main
    path: overlays/prod/platform

  destination:
    server: 'https://fiaptc3-dns-l25hulwg.hcp.eastus.azmk8s.io:443'
    namespace: toggle-apps

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        projeto: togglemaster
